### ISSUE TITLE
你好，与Chromium 69不兼容，无法显示标签页预览图了。可以更新一下吗？这个插件超级好用~

### ISSUE THREAD

**Issue by 137943103** [achekulaev/tabspane#4]

**Comment by achekulaev** [comment]
Previews are working fine. But you need to visit the tab at least once for security reasons.

**Comment by achekulaev** [comment]
<img width="702" alt="tabs pane 2018-11-14 22-41-51" src="https://user-images.githubusercontent.com/402007/48528822-8e7e1e80-e85e-11e8-82d4-d7a7e64e0139.png">

**Comment by 137943103** [comment]
Please click on the URL to see my recorded video, thank you！
https://pan.baidu.com/s/1sS-wjrILa3SUk3gfhhU2yg

**Comment by 137943103** [comment]
Chromium 70.0.3538.110

**Comment by 137943103** [comment]
![image](https://user-images.githubusercontent.com/45056093/49629664-92e4c400-fa25-11e8-8ad1-a304eb12518e.png)
